# Run: sudo docker compose -f perpetuals-testnet.yml up --build -d

version: "2"

services:
  # Redis
  ## For Pub/Sub between blockchain listener (pub) and executors (sub)
  redis:
    image: redis
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: on-failure

  # Blockain Streamer
  ## Listen to block and events, and stream on redis
  blockchain-streamer:
    build:
      context: .
      dockerfile: ./src/listener/Dockerfile
    depends_on:
      - redis
    environment:
      - CHAIN_ID=${CHAIN_ID}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  # Executors
  ## One service per bot/perpetual.

  eth-usd-matic:
    depends_on:
      - blockchain-streamer
    build:
      context: .
    extends:
      file: base.yml
      service: base
    environment:
      - SYMBOL=ETH-USD-MATIC
      - WALLET_INDEX=1

  btc-usd-matic:
    depends_on:
      - blockchain-streamer
    extends:
      file: base.yml
      service: base
    environment:
      - SYMBOL=BTC-USD-MATIC
      - WALLET_INDEX=2

  matic-usd-matic:
    depends_on:
      - blockchain-streamer
    extends:
      file: base.yml
      service: base
    environment:
      - SYMBOL=MATIC-USD-MATIC
      - WALLET_INDEX=3

  eth-usdc-usdc:
    depends_on:
      - blockchain-streamer
    extends:
      file: base.yml
      service: base
    environment:
      - SYMBOL=ETH-USDC-USDC
      - WALLET_INDEX=4

  matic-usdc-usdc:
    depends_on:
      - blockchain-streamer
    extends:
      file: base.yml
      service: base
    environment:
      - SYMBOL=MATIC-USDC-USDC
      - WALLET_INDEX=5

  btc-usdc-usdc:
    depends_on:
      - blockchain-streamer
    extends:
      file: base.yml
      service: base
    environment:
      - SYMBOL=BTC-USDC-USDC
      - WALLET_INDEX=6

  chf-usdc-usdc:
    depends_on:
      - blockchain-streamer
    extends:
      file: base.yml
      service: base
    environment:
      - SYMBOL=CHF-USDC-USDC
      - WALLET_INDEX=7

  gbp-usdc-usdc:
    depends_on:
      - blockchain-streamer
    extends:
      file: base.yml
      service: base
    environment:
      - SYMBOL=GBP-USDC-USDC
      - WALLET_INDEX=8

  xau-usdc-usdc:
    depends_on:
      - blockchain-streamer
    extends:
      file: base.yml
      service: base
    environment:
      - SYMBOL=XAU-USDC-USDC
      - WALLET_INDEX=9
