# Default prometheus config used to scrape the executor service and send alerts
# to alertmanager. Note that hostnames are used as defined in
# docker-compose.yml, therfore any change in compose file must be reflected here
# too.

global:
  scrape_interval: "30s"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - /etc/prometheus/rules/*.rules.yaml

scrape_configs:
- job_name: executor
  static_configs:
  - targets:
    - executor:9001
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
